version: '3.8'

services:
  yandex-tv-schedule:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    env_file:
      - stack.env
    command: python /app/main.py
    working_dir: /app
    restart: unless-stopped
    