version: '3.8'

services:
  db:
    image: postgres:latest 
    container_name: test_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-public}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: